<?php

namespace App\Controller;

use App\Entity\Documentos;
use App\Form\DocumentosType;
use App\Repository\DocumentosRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

/**
 * @Route("/documentos")
 */
class DocumentosController extends AbstractController
{
    /**
     * @Route("/", name="documentos_index", methods={"GET"})
     */
    public function index(DocumentosRepository $documentosRepository): Response
    {
        return $this->render('documentos/index.html.twig', [
            'documentos' => $documentosRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="documentos_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $documento = new Documentos();
        $form = $this->createForm(DocumentosType::class, $documento);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
                        $arquivo = $documento->getImagem();
                        $nomeArquivo = $this->generateUniqueFileName().'.'.$arquivo->guessExtension();
                        try {
                            $arquivo->move(
                                $this->getParameter('img_diretorio'),
                                $nomeArquivo
                            );
                        } catch(FileException $fe)  {
                            $this->addFlash('success',sprintf('Erro: %s', $fe->getMessage()));
                            return [
                                'form' => $form->createView()
                            ];
                        }
                        $documento->setImagem($nomeArquivo);
                        $entityManager = $this->getDoctrine()->getManager();
                        $entityManager->persist($documento);
                        $entityManager->flush();
                        return $this->redirectToRoute('documentos_index');
        }

        return $this->render('documentos/new.html.twig', [
            'documento' => $documento,
            'form' => $form->createView(),
        ]);
    }
        // $pdfClicked = $form->get('.btn')->isClicked();
        // if ($pdfClicked) {
           
        // }
        private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    
    }

    

    /**
     * @Route("/{id}", name="documentos_show", methods={"GET"})
     */
    public function show(Documentos $documento): Response
    {
        return $this->render('documentos/show.html.twig', [
            'documento' => $documento,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="documentos_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Documentos $documento): Response
    {
        $form = $this->createForm(DocumentosType::class, $documento);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $form->setImagem(new File($this->getParameter('uploads/img').'/'.$imagem->getImagem()));
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('documentos_index', [
                'id' => $documento->getId(),
            ]);
        }

        return $this->render('documentos/edit.html.twig', [
            'documento' => $documento,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="documentos_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Documentos $documento): Response
    {
        if ($this->isCsrfTokenValid('delete'.$documento->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($documento);
            $entityManager->flush();
        }

        return $this->redirectToRoute('documentos_index');

        
    }
     /**
     * @Route("/delimg/{id}", name="documentos_deleteimg", methods={"DELETEIMG"})
     */
    public function deleteimg(Request $request, Documentos $documento): Response
    {
        if ($this->isCsrfTokenValid('delete'.$documento->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($documento);
            $entityManager->flush();
        }

        return $this->redirectToRoute('documentos_index');
    }
}
